### ISSUE TITLE
Get basic read-only information from Libvirt, make VDSM connectivity optional

### ISSUE THREAD

**Issue by xsgordon** [mareklibra/cockpit-ovirt#30]
The basic read-only information presented by the plug-in could be obtained directly from Libvirt, the reason this would be desirable is that forcing this via VDSM ensures this can currently *only* be used with oVirt even for basic use cases (e.g. single host virt).

If the basic information was provided directly from Libvirt the plugin could still be used for basic virtualization, with advanced functionality enabled by optionally connecting to VDSM and/or RHEV-M. 

Longer term this would also make it possible to optionally enable alternative management engines (OpenStack) via the same shared plugin rather than having to build 2-3 completely separate plug-ins duplicating the basic functionality all of which would ideally just come up as a "Virtualization" tab in cockpit.

**Comment by mareklibra** [comment]
@xsgordon, recent version of upstream Cockpit contains VM monitoring based on libvirt. Please let me know whether/how it meets your (OpenStack?) needs.

In addition, there's ongoing work on enabling different providers for the VM monitoring in upstream.
