### ISSUE TITLE
Centos 7 - this shit simply doesn't work

### ISSUE THREAD

**Issue by marksaitis** [mareklibra/cockpit-ovirt#31]
ovirt hyperconverged cockpit wizard - whatever config you select in the wizard, the damn thing in the end produces a configuration of whatever it wants. It takes nothing from what you input in the wizard. What the hell is the point of you guys making this software if it doesn't do what it's supposed to do? Don't put the damn package in the repo's of centos if it is broken. I thought I will give centos a go because of this ovirt, but f this garbage here. What a pile of crap. Anything debian/ubuntu made contains 10 times less nonsense over my 20 years experience in Linux.

**Comment by mykaul** [comment]
This issue should be closed.
Please see community guidelines[1]. Be respectful.

[1] https://www.ovirt.org/community/about/community-guidelines.html

**Comment by mykaul** [comment]
cc @jelkosz - please close.
